project:
  type: website
  render: 
    - "*.qmd"
  output-dir: docs
  preview:
    port: 4200

website:
  page-footer:
    center:
      - text: "Términos y Condiciones"
        href: terminos.qmd
      - text: "Código de conducta"
        href: codigo_conducta.qmd
    left: |
      Contenido {{< fa brands creative-commons >}} 2024 por Aprende Tidyverse<br>
      Todo el contenido está licenciado bajo una Licencia Internacional Creative Commons Atribución-NoComercial 4.0 ([CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.es)).
    right: |
      Hecho con {{< fa heart >}} desde Costa Rica usando {{< fa brands r-project >}} y [Quarto](https://quarto.org/)<br>
      [Revisa el código fuente en {{< fa brands github >}} GitHub](https://github.com/aguerodev/aguerodev.github.io)
  cookie-consent:
    type: express
    style: headline
    palette: light
  google-analytics:
    tracking-id: "G-7HH46G4FS3"
    anonymize-ip: true
  bread-crumbs: true
  open-graph:
    locale: es_ES
    site-name: aprendetidyverse.com
  twitter-card:
    creator: "@dev_aguero"
    site: "@dev_aguero"
  title: "Aprende Tidyverse"
  favicon: favicon.ico
  navbar:
    logo: images/logo.png
    logo-alt: ""
    title: false
    background: dark
    left:
      - text: "Inicio"
        file: index.qmd
      - text: "Cursos"
        menu:
          - text: "Programa de completo 5 cursos"
          - text: "Fundamentos de R y Rstudio"
            icon: "bi-laptop"
            href: courses/fundamentos_R.qmd
          - text: "Visualización de datos con R"
            icon: "palette"
            href: courses/visualizacion_datos_R.qmd
          - text: "Limpieza y Manipulación de datos con R"
            icon: "tools"
            href: courses/manipulacion_datos_R.qmd
          - text: "Introducción a SQL y su integración con R"
            icon: "bi-database"
            href: courses/introduccion_sql.qmd
          - text: "Web Scraping y Automatización con R"
            icon: "bi-globe"
            href: courses/web_scraping.qmd
      - text: "Ayuda con R"
        href: domingos_pr.qmd
      - text: Blog
        file: posts.qmd

    right:
      - icon: twitter
        href: https://twitter.com/dev_aguero
      - icon: instagram
        href: https://www.instagram.com/aprende.tidyverse/
      - icon: facebook
        href: https://www.facebook.com/aprende.tidyverse
      - icon: linkedin
        href: https://www.linkedin.com/in/carlos-aguero-cr/
  site-url: https://aprendetidyverse.com
  repo-url: https://github.com/aguerodev/aguerodev.github.io


format:
  html:
    grid:
      sidebar-width: 280px
    theme: seem.scss
    highlight-style: seem.theme
    metadata:
      pagetitle: "{{< meta title >}}"
      freeze: true
      # Enable banner style title blocks
      title-block-banner: false
      # Can't yet enable this because it causes "On this page" to appear on index.html
      # even if I set its post-level `toc: false`
      # toc: true
      title-block-categories: false
      toc-depth: 5
      
metadata-files:
  - drafts.yml
