project:
  type: website
  render: 
    - "*.qmd"
  output-dir: docs
  preview:
    port: 4200

website:
  cookie-consent:
    type: express
    style: headline
    palette: light
  google-analytics:
    tracking-id: "G-7HH46G4FS3"
    anonymize-ip: true
  bread-crumbs: true
  open-graph:
    locale: es_ES
    site-name: aprendetidyverse.com
  twitter-card:
    creator: "@dev_aguero"
    site: "@dev_aguero"
  title: "Aprende Tidyverse"
  favicon: favicon.ico
  navbar:
    background: dark
    left:
      - text: "Curso R para ciencia de datos"
        file: classes/intro.qmd
      - text: Blog
        file: posts.qmd
    right:
      - icon: twitter
        href: https://twitter.com/dev_aguero
      - icon: instagram
        href: https://www.instagram.com/aprende.tidyverse/
      - icon: facebook
        href: https://www.facebook.com/aprende.tidyverse
      - icon: linkedin
        href: https://www.linkedin.com/in/carlos-aguero-cr/
  sidebar:
    - id: semana_1 
      background: light
      title: "Semana 1"
      collapse-level: 1
      contents:
        - section: "Antes de comenzar"
          contents:
            - href: classes/intro.qmd
            - href: classes/prep.qmd
        - text: "---"
        - section: "Semana 1"
          contents:
            - href: classes/class_01.qmd
            - href: classes/class_01.2.qmd
            - href: classes/class_01.3.qmd
            - href: classes/class_01.4.qmd
            - href: classes/class_01.5.qmd
            - href: classes/cal_com.qmd
        - text: "---"
        - section: "Semana 2"
          contents:
            - href: classes/class_02.qmd
            - href: classes/cal_com.qmd
        - text: "---"
        - section: "Semana 3"
          contents:
            - href: classes/class_03.qmd
            - href: classes/cal_com.qmd
        - text: "---"
        - section: "Semana 4"
          contents:
            - href: classes/class_04.qmd
            - href: classes/cal_com.qmd
        - text: "---"
        - section: "Semana 5"
          contents:
            - href: classes/class_05.qmd
            - href: classes/cal_com.qmd
        - text: "---"
        - section: "Semana 6"
          contents:
            - href: classes/class_06.qmd
            - href: classes/cal_com.qmd
        - text: "---"
        - section: "Semana 7"
          contents:
            - href: classes/class_07.qmd
            - href: classes/cal_com.qmd
        - text: "---"
        - section: "Semana 8"
          contents:
            - href: classes/class_08.qmd
            - href: classes/cal_com.qmd
        - text: "---"
        - section: "Semana 9"
          contents:
            - href: classes/class_09.qmd
            - href: classes/cal_com.qmd
        - text: "---"
        - section: "Semana 10"
          contents:
            - href: classes/class_10.qmd
            - href: classes/cal_com.qmd
        - text: "---"
        - section: "Semana 11"
          contents:
            - href: classes/class_11.qmd
            - href: classes/cal_com.qmd
        - text: "---"
        - section: "Semana 12"
          contents:
            - href: classes/class_12.qmd
            - href: classes/cal_com.qmd
  site-url: https://aprendetidyverse.com
  repo-url: https://github.com/aguerodev/aguerodev.github.io

format:
  html:
    grid:
      sidebar-width: 280px
    theme: seem.scss
    highlight-style: seem.theme
    metadata:
      pagetitle: "{{< meta title >}}"
      freeze: true
      # Enable banner style title blocks
      title-block-banner: false
      author: Carlos Aguero B
      # Can't yet enable this because it causes "On this page" to appear on index.html
      # even if I set its post-level `toc: false`
      # toc: true
      title-block-categories: false
      toc-depth: 5


