---
title: R para ciencia de datos
subtitle: Convirtiendo datos en decisiones poderosas
toc: true
comments: false
author: ''
---

### [Inscríbete ahora inicio de clases 6 de marzo ](https://buy.stripe.com/3cs7svcVoaVQ1fG8wy).

En mi último año de carrera en ingeniería en sistemas de información, descubrí un tesoro: "[R for Data Science](https://r4ds.hadley.nz)" de Hadley Wickham y Garrett Grolemund en su primera edición. Este libro no era simplemente un manual; era una revelación, mostrándome un universo completamente nuevo dentro del lenguaje R, conocido como tidyverse. A lo largo de los años, he tenido el privilegio de enseñar ciencia de datos a **más de 400 estudiantes de más de 5 países de América Latina**, viendo cómo este enfoque transformaba la manera en que abordamos los datos.

Hoy, 8 años más tarde, el cambio es palpable. Tidyverse ha madurado de forma sorprendente, democratizando el análisis de datos. Permite a aquellos sin un trasfondo en programación adentrarse en la lectura, limpieza, análisis, y visualización de datos con una lógica coherente y un código diseñado para ser fácilmente comprensible. Durante el 2020, en el apogeo de la pandemia, fui parte de una iniciativa de RStudio que buscaba formar [instructores capacitados para enseñar R](https://education.rstudio.com/trainers/), especialmente a no programadores. Tuve el honor de ser alumno de Greg Wilson, cofundador de [The Carpentries](https://carpentries.org) y autor de [Teaching Tech Together](https://teachtogether.tech/en/index.html), una obra que considero esencial para quien desee enseñar programación de manera efectiva.

Con estos pilares de conocimiento y experiencia, hemos diseñado este curso dirigido **especialmente a no informáticos**. Este programa no solo busca impartir habilidades prácticas y aplicables en ciencia de datos de manera intuitiva y sencilla, sino que también se enfoca en la resolución de problemas cotidianos. Desde fútbol hasta películas, música y cuestiones sociales, exploraremos cómo utilizar R y tidyverse como herramientas para convertirnos en solucionadores de problemas. Este es más que un curso; es una invitación a cambiar la forma en que ves el mundo a través de los datos.

## Descripción del curso

:::: {.columns}

::: {.column width="50%"}

#### 🚀 Características del Curso
- **Duración:** 6 semanas.
- **Modalidad:** En vivo, a través de Zoom, promoviendo la interacción y el aprendizaje activo.
- **Frecuencia:** Clases 2 veces a la semana (miércoles y sábados).
- **Horario:** 6 p.m. Hora de Costa Rica (UTC -6).


:::

::: {.column width="50%"}
#### 📚 Estructura del Curso
- **Lecciones en Vivo:** 12 clases, aproximadamente 2 horas cada una.
- **Sesiones de Seguimiento Privadas:** 6 sesiones de 45 minutos con el instructor para personalizar tu aprendizaje.
- **Grabaciones:** Acceso a grabaciones de cada clase, enviadas por correo electrónico 24 horas después.

:::


::: {.column width="100%"}
#### 💳 Costo e Información de Pago
- **Costo:** $300 USD.
- **Métodos de Pago:** Aceptamos pagos vía tarjeta de crédito o débito via [Stripe](https://stripe.com/es-us), la plataforma de pagos en linea más utilizada por grantes empresas.
- **Métodos de Pago Alternativos:** En el caso de los estudiantes de Costa Rica puede hacer el pago de forma manual mediente una tranferencia bancaria para esto escribe a info@aprendetidyverse.com para solicitar hacer el pago por este medio.
- **Inscríbete ahora:** [Enlace de pago](https://buy.stripe.com/3cs7svcVoaVQ1fG8wy).


:::

::::

Si tienes dudas programa una 🎥 [sesión de 15 minutos con el instructor via zoom](https://cal.com/aprendetidyverse/15min) para resolver dudas y revisar temas de interés. ¡Asegura que el curso cumpla con tus expectativas!

## Testimonios y comentarios

<iframe height="800px" id='testimonialto-r-para-ciencia-de-datos-tag-all-light-animated' src="https://embed-v2.testimonial.to/w/r-para-ciencia-de-datos?animated=on&theme=light&shadowColor=ffffff&speed=1&hideSource&tag=all" frameborder="0" scrolling="no" width="100%"></iframe>

Puedes leer más comentarios en mi [perfil de linkedin](https://www.linkedin.com/in/carlos-aguero-cr/details/recommendations)

## Temario del curso

<details open>
  <summary> Clase 1: Descubriendo R y el Tidyverse</summary>
  Esta clase te introduce a R y el conjunto de herramientas del Tidyverse. Aquí aprenderás a configurar tu espacio de trabajo en RStudio, cómo leer archivos .csv y empezarás a jugar con tus datos, dándoles un primer vistazo y creando visualizaciones sencillas.
</details>


<details>
  <summary> Clase 2: Comenzamos a explorar los datos</summary>
  En esta clase, te adentrarás en el corazón de `dplyr` y `tidyr`, donde la magia de la manipulación de datos realmente sucede. Aprenderás a filtrar, seleccionar, y transformar tus datos para revelar las historias ocultas que tienen para contar.
</details>


<details>
  <summary> Clase 3: Inicia en la visualización de Datos</summary>
  Aquí, vas a llevar tus habilidades de visualización al siguiente nivel, usando `ggplot2` para crear tus primeros gráfico. Aprenderás sobre escalas, facetas, y cómo personalizar tus gráficos para que destaquen y se adapte a tus necesidades.
</details>

<details>
  <summary> Clase 4: Lectura y limpieza de datos</summary>
  Esta clase te enseñará a ser capaz de leer datos almacenados en `CSV`, `Excel`, `SPSS`, entre otros. Ya sea que estés trabajando con `texto`, `números`, `fechas`, o cualquier otro tipo, aprenderás las habilidades para manejarlos todos con eficiencia.
</details>

<details>
  <summary> Clase 5: El arte de trabajar con textos y techas</summary>
Las **expresiones regulares** y el **manejo de fechas** pueden parecer hechizos complicados, pero después de esta clase, serán herramientas poderosas en tu arsenal. Aprenderás a limpiar y filtrar tus datos de manera eficiente con los paquetes `stringr` y `lubridate` convirtiendo el caos en orden con solo unas pocas líneas de código.
</details>


<details>
  <summary>Clase 6: Entendiendo los datos relacionales</summary>
En esta clase te enseña a unir diferentes conjuntos de datos para descubrir conexiones ocultas. Dominarás los `joins` y aprenderás sobre las `llaves` y las `relaciones`, lo que te permitirá combinar datos de fuentes diversas para obtener insights más profundos.
</details>

<details>
  <summary>Clase 7: Explorando con gráficos avanzados</summary>
Con `ggplot2` y `plotly`, esta clase aprenderás a crear gráficos interactivos y explorar **datos geoespaciales**, llevando tus habilidades narrativas a nuevas dimensiones.
</details>

<details>
  <summary>Clase 8: Conecta R con el mundo las bases de datos SQL</summary>
Aquí, R se encuentra con el poder de las bases de datos SQL. Aprenderás a realizar consultas SQL directamente desde R, lo que te permite acceder a y manipular grandes conjuntos de datos almacenados en bases de datos de manera eficiente.
</details>

<details>
  <summary>Clase 9: La Elegancia de la programación funcional</summary>
Con `purrr`, transformarás tu enfoque de manejar datos. Aprenderás a escribir funciones personalizadas y a iterar sobre tus datos de formas que hacen que el código no solo sea más limpio, sino también más expresivo.
</details>

<details>
  <summary>Clase 10: Extrayendo datos de la web</summary>
El web scraping y las APIs abren un universo de datos disponibles en internet. Esta clase te equipará con las herramientas para recoger estos datos como `rvest` y `httr2`, permitiéndote responder preguntas que antes parecían inalcanzables.
</details>

<details>
  <summary>Clase 11: Creando documento con quarto</summary>
Con `Quarto`, aprenderás a combinar tu análisis con narrativas en reportes dinámicos, haciendo que tus hallazgos no solo sean comprensibles, sino también atractivos para tu audiencia. Es la habilidad de contar una historia cautivadora, donde los datos son los personajes principales.
</details>

<details>
  <summary>Clase 12: Manejo de proyectos de datos</summary>
Finalmente, dominarás el arte de gestionar proyectos de datos con `Git`, `GitHub`, y entornos virtuales `renv.` Esto te asegura que tus proyectos sean reproducibles, colaborativos, y organizados.
</details>

## Inscripción

📅 **Comienza Tu Aventura:** Recuerda que el inicio de clases es el miércoles 6 de marzo de 2024, [**Inscríbete ahora**](https://buy.stripe.com/3cs7svcVoaVQ1fG8wy).

Una vez hayas confirmado el pago, recibirás por correo electrónico (al correo que utilizaste para realizar el pago) la confirmación junto con todos los datos relevantes, incluyendo los enlaces de acceso y fechas importantes.

Si tienes dudas programa una [sesión de 15 minutos con el instructor](https://cal.com/aprendetidyverse/15min) para resolver dudas y revisar temas de interés. ¡Asegura que el curso cumpla con tus expectativas!

Puedes escríbeme a <a href="mailto:carlos.aguero@aprendetidyverse.com">carlos.aguero@aprendetidyverse.com</a>. También puedes encontrarme en [LinkedIn](https://www.linkedin.com/in/carlos-aguero-cr) o en [Twitter](https://twitter.com/dev_aguero)




